### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/pw2-e2-Arzival#1]
La tabla está mal estructurada, no puede haber una celda en una fila y en otra 10. Revisa la documentación HTML1 sobre tablas.
https://github.com/UniversidadCristobalColon/pw2-e2-Arzival/blob/d5ad9528b5259d4e735a7e6a7ba7a608aea7a872/index.html#L37

**Comment by Arzival** [comment]
corregida la tabla
